language: go

go:
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - master

install:
  - make deps

script:
  - make lint
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
