language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - make deps

script:
  - make lint
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
