language: go
os: linux
dist: bionic

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master

jobs:
  allow_failures:
    - go: master

env:
  global:
    - GO111MODULE=on

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - go mod download

script:
  - make lint
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
