name: Continuous Integration
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request: { }
  workflow_dispatch: { }
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: golangci/golangci-lint-action@v3

      - run: make lint
      - run: make test

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
